#!/bin/bash
#SBATCH --job-name=nlp2brain_regions_multi
#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gpus-per-node=1
#SBATCH --time=1:00:00
#SBATCH --output=logs/%x_%j.out

cd /home/scur0418/NLP2BrainEmbed

module purge
module load 2023
module load Python/3.11.3-GCCcore-12.3.0
module load CUDA/12.1.1
source $HOME/venvs/nlp2brain/bin/activate

export HF_HOME=/scratch-shared/$USER/hf_dir
export HF_HUB_CACHE=/scratch-shared/$USER/hf_dir
mkdir -p logs data results/regions

MODEL_NAME=Qwen/Qwen3-Embedding-4B
MODEL_KEY=embedding

PARTICIPANTS=(P01 M02 M03 M04 M07 M15)

REGIONS=(
    languageLH
    languageRH
    DMN
    MD
)

for P in "${PARTICIPANTS[@]}"; do
    for REGION in "${REGIONS[@]}"; do
        TAG=${P}_qwen3-4b-${MODEL_KEY}_passages_${REGION}

        echo "=============================================="
        echo "Participant: ${P}"
        echo "Region: ${REGION}"
        echo "Tag:    ${TAG}"
        echo "=============================================="

        python scripts/extract_embeddings.py \
            --mat-path MRI_data/${P}/data_243sentences.mat \
            --model-name $MODEL_NAME \
            --pooling last \
            --region ${REGION} \
            --output data/regions/${TAG}.npz \
            --level passage --dtype float16

        python scripts/run_encoding.py \
            --mat-path MRI_data/${P}/data_243sentences.mat \
            --embeddings data/regions/${TAG}.npz \
            --region ${REGION} \
            --output-dir results/regions/${TAG} \
            --level passage \
            --save-voxelwise
    done
done